package abc

import (
	"strings"
)

//ToSingle returns the single form of the given english word.
func ToSingle(word string) string {
	if len(word) == 0 {
		return ""
	}

	lower := strings.ToLower(word)

	if single, ok := singles[lower]; ok {
		return single
	}
	if _, ok := plurals[lower]; ok {
		return word
	}

	for i := min(len(word), len(suffixToSingle)-1); i > 0; i-- {
		suffix := word[len(word)-i:]

		if rule, ok := suffixToSingle[i][suffix]; ok {
			return word[:len(word)-i] + rule
		}
	}

	return strings.TrimSuffix(word, "s")
}

var singles = map[string]string{
	"aircraft":     "aircraft",
	"aliases":      "alias",
	"alumnae":      "alumna",
	"alumni":       "alumnus",
	"analyses":     "analysis",
	"antennas":     "antenna",
	"antitheses":   "antithesis",
	"apexes":       "apex",
	"appendices":   "appendix",
	"axes":         "axis",
	"bacilli":      "bacillus",
	"bacteria":     "bacterium",
	"bases":        "basis",
	"beaus":        "beau",
	"bison":        "bison",
	"bureaus":      "bureau",
	"buses":        "bus",
	"campuses":     "campus",
	"caucuses":     "caucus",
	"children":     "child",
	"châteaux":     "château",
	"circuses":     "circus",
	"codices":      "codex",
	"concertos":    "concerto",
	"corpora":      "corpus",
	"crises":       "crisis",
	"curriculums":  "curriculum",
	"data":         "datum",
	"deer":         "deer",
	"diagnoses":    "diagnosis",
	"dice":         "die",
	"dwarves":      "dwarf",
	"ellipses":     "ellipsis",
	"equipment":    "equipment",
	"errata":       "erratum",
	"faux pas":     "faux pas",
	"fezzes":       "fez",
	"fish":         "fish",
	"foci":         "focus",
	"foos":         "foo",
	"feet":         "foot",
	"formulas":     "formula",
	"fungi":        "fungus",
	"genera":       "genus",
	"geese":        "goose",
	"graffiti":     "graffito",
	"grouse":       "grouse",
	"halves":       "half",
	"halos":        "halo",
	"hooves":       "hoof",
	"humans":       "human",
	"hypotheses":   "hypothesis",
	"indices":      "index",
	"information":  "information",
	"jeans":        "jeans",
	"larvae":       "larva",
	"librettos":    "libretto",
	"loaves":       "loaf",
	"loci":         "locus",
	"lice":         "louse",
	"matrices":     "matrix",
	"minutiae":     "minutia",
	"money":        "money",
	"moose":        "moose",
	"mice":         "mouse",
	"nebulae":      "nebula",
	"news":         "news",
	"nuclei":       "nucleus",
	"oases":        "oasis",
	"octopi":       "octopus",
	"offspring":    "offspring",
	"opera":        "opus",
	"ova":          "ovum",
	"oxen":         "ox",
	"parentheses":  "parenthesis",
	"phenomena":    "phenomenon",
	"photos":       "photo",
	"phyla":        "phylum",
	"pianos":       "piano",
	"pluses":       "plus",
	"police":       "police",
	"prognoses":    "prognosis",
	"prometheuses": "prometheus",
	"quizzes":      "quiz",
	"quotas":       "quota",
	"radiuses":     "radius",
	"referendums":  "referendum",
	"resses":       "ress",
	"rice":         "rice",
	"salmon":       "salmon",
	"sexes":        "sex",
	"series":       "series",
	"sheep":        "sheep",
	"shoes":        "shoe",
	"shrimp":       "shrimp",
	"species":      "species",
	"stimuli":      "stimulus",
	"strata":       "stratum",
	"swine":        "swine",
	"syllabi":      "syllabus",
	"symposiums":   "symposium",
	"synapses":     "synapse",
	"synopses":     "synopsis",
	"tableaus":     "tableau",
	"testes":       "testis",
	"theses":       "thesis",
	"thieves":      "thief",
	"teeth":        "tooth",
	"trout":        "trout",
	"tuna":         "tuna",
	"vedalias":     "vedalia",
	"vertebrae":    "vertebra",
	"vertices":     "vertix",
	"vitae":        "vita",
	"vortices":     "vortex",
	"wharves":      "wharf",
	"wives":        "wife",
	"women":        "woman",
	"wolves":       "wolf",
	"you":          "you",
}

var suffixToSingle = [9]map[string]string{
	2: {
		"ia": "ium",
		"li": "leus",
		"ta": "tum",
	},
	3: {
		"ata": "atum",
		"eet": "oot",
		"ios": "io",
		"iri": "irus",
		"men": "man",
		"mni": "mnus",
		"oes": "o",
		"ova": "ovum",
		"ria": "rion",
		"vae": "va",
		"xes": "x",
		"you": "you",
	},
	4: {
		"acti": "actus",
		"adia": "adium",
		"aves": "afe",
		"bies": "by",
		"bves": "bfe",
		"ches": "ch",
		"cies": "cy",
		"cves": "cfe",
		"dges": "dge",
		"dies": "dy",
		"dves": "dfe",
		"eese": "oose",
		"esis": "eses",
		"eves": "efe",
		"fies": "fy",
		"foci": "focus",
		"gies": "gy",
		"gves": "gfe",
		"hies": "hy",
		"hves": "hfe",
		"ices": "ex",
		"ises": "isis",
		"ives": "ife",
		"izes": "ize",
		"jies": "jy",
		"jves": "jfe",
		"kies": "ky",
		"kves": "kfe",
		"lice": "louse",
		"lies": "ly",
		"lves": "lf",
		"mice": "mouse",
		"mies": "my",
		"mves": "mfe",
		"news": "news",
		"nies": "ny",
		"nnas": "nna",
		"nves": "nfe",
		"ocus": "oci",
		"odes": "ode",
		"oves": "ofe",
		"pies": "py",
		"psis": "pse",
		"pves": "pfe",
		"qies": "qy",
		"qves": "qfe",
		"ries": "ry",
		"rves": "rf",
		"shes": "sh",
		"sies": "sy",
		"sses": "ss",
		"stes": "stis",
		"sves": "sfe",
		"ties": "ty",
		"tves": "tfe",
		"tzes": "tz",
		"ulas": "ula",
		"ulus": "uli",
		"uses": "use",
		"uves": "ufe",
		"vies": "vy",
		"vves": "vfe",
		"wies": "wy",
		"wves": "wfe",
		"xies": "xy",
		"xves": "xfe",
		"yves": "yfe",
		"zies": "zy",
		"zves": "zfe",
		"zzes": "zz",
	},
	5: {
		"bases": "base",
		"basis": "basis",
		"boxes": "box",
		"diums": "dium",
		"genus": "genera",
		"hives": "hive",
		"ianos": "iano",
		"itzes": "itz",
		"jeans": "jeans",
		"media": "media",
		"moves": "move",
		"oasis": "oasis",
		"oaves": "oaf",
		"odice": "odex",
		"ouses": "ouse",
		"phyla": "phylum",
		"quies": "quy",
		"randa": "randum",
		"shoes": "shoe",
		"tives": "tive",
		"tuses": "tus",
		"usses": "uss",
		"wives": "wife",
	},
	6: {
		"atuses": "atus",
		"cesses": "cess",
		"chives": "chive",
		"halves": "half",
		"hellos": "hello",
		"iteria": "iterion",
		"movies": "movie",
		"people": "person",
	},
	8: {
		"campuses": "campus",
		"children": "child",
	},
}
